CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(80) NOT NULL,
  email VARCHAR(180) NULL,
  phone VARCHAR(32) NULL,
  password_hash VARCHAR(255) NULL,
  password VARCHAR(255) NULL,
  role ENUM('admin','reseller','member') NOT NULL DEFAULT 'member',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  saldo DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  locked_balance DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  bot_access_unlocked TINYINT(1) NOT NULL DEFAULT 0,
  bot_disabled_reason VARCHAR(255) NULL,
  bot_session_id VARCHAR(120) NULL,
  bot_connected_number VARCHAR(40) NULL,
  bot_last_active_at TIMESTAMP NULL,
  bot_session_status ENUM('not_connected','connecting','connected','disconnected','logged_out') NOT NULL DEFAULT 'not_connected',
  api_key VARCHAR(128) NULL,
  reseller_request_status VARCHAR(32) NOT NULL DEFAULT 'none',
  reseller_request_reason TEXT NULL,
  reseller_request_whatsapp VARCHAR(40) NULL,
  reseller_request_experience TEXT NULL,
  reseller_request_rejected_reason TEXT NULL,
  reseller_requested_at TIMESTAMP NULL,
  reseller_reviewed_at TIMESTAMP NULL,
  markup_custom DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  markup_percent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  reseller_margin_percent DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  theme VARCHAR(16) NOT NULL DEFAULT 'dark',
  fullName VARCHAR(180) NULL,
  orders INT UNSIGNED NOT NULL DEFAULT 0,
  deposits INT UNSIGNED NOT NULL DEFAULT 0,
  notes TEXT NULL,
  last_login_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_username (username),
  UNIQUE KEY uq_users_email (email),
  UNIQUE KEY uq_users_phone (phone),
  UNIQUE KEY uq_users_api_key (api_key),
  UNIQUE KEY uq_users_bot_session_id (bot_session_id),
  KEY idx_users_role (role),
  KEY idx_users_bot_session_status (bot_session_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  premku_id VARCHAR(80) NULL,
  provider_product_id VARCHAR(80) NULL,
  code VARCHAR(80) NOT NULL,
  name VARCHAR(180) NOT NULL,
  note TEXT NULL,
  description TEXT NULL,
  category VARCHAR(120) NULL,
  tag VARCHAR(120) NULL,
  image TEXT NULL,
  image_url TEXT NULL,
  tutorial_url TEXT NULL,
  stock INT UNSIGNED NOT NULL DEFAULT 0,
  provider_stock_count INT UNSIGNED NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  product_source VARCHAR(32) NOT NULL DEFAULT 'provider',
  is_manual TINYINT(1) NOT NULL DEFAULT 0,
  manual_stock_count INT UNSIGNED NOT NULL DEFAULT 0,
  base_price DECIMAL(15,2) UNSIGNED NULL,
  admin_margin DECIMAL(15,2) UNSIGNED NULL,
  member_markup DECIMAL(15,2) UNSIGNED NULL,
  reseller_markup DECIMAL(15,2) UNSIGNED NULL,
  member_price DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  reseller_price DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  discount_label_percent DECIMAL(5,2) UNSIGNED NULL,
  raw_response JSON NULL,
  synced_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_products_code (code),
  KEY idx_products_premku_id (premku_id),
  KEY idx_products_provider_product_id (provider_product_id),
  KEY idx_products_status (status),
  KEY idx_products_product_source (product_source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_stock_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  email_account VARCHAR(255) NULL,
  password_account TEXT NULL,
  description TEXT NULL,
  status ENUM('available','reserved','used','disabled') NOT NULL DEFAULT 'available',
  reserved_by_order_invoice VARCHAR(80) NULL,
  used_by_order_invoice VARCHAR(80) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  reserved_at TIMESTAMP NULL,
  used_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_product_stock_items_product_id (product_id),
  KEY idx_product_stock_items_status (status),
  KEY idx_product_stock_items_reserved_by_order_invoice (reserved_by_order_invoice),
  KEY idx_product_stock_items_used_by_order_invoice (used_by_order_invoice)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reseller_bot_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  brand_name VARCHAR(120) NOT NULL DEFAULT 'PREMIUMIN PLUS BOT',
  greeting_hooks VARCHAR(255) NOT NULL DEFAULT 'p,ping,halo,haloo,bro',
  welcome_message TEXT NULL,
  admin_whatsapp VARCHAR(40) NULL,
  operational_hours VARCHAR(120) NOT NULL DEFAULT '08.00 - 21.00 WIB',
  closing_message TEXT NULL,
  catalog_template VARCHAR(32) NOT NULL DEFAULT 'template_1',
  order_template VARCHAR(32) NOT NULL DEFAULT 'template_1',
  terms_text TEXT NULL,
  reseller_margin_type VARCHAR(16) NOT NULL DEFAULT 'percent',
  reseller_margin_value DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 10.00,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_reseller_bot_settings_user_id (user_id),
  KEY idx_reseller_bot_settings_is_active (is_active),
  CONSTRAINT fk_reseller_bot_settings_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice VARCHAR(80) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  transaction_type VARCHAR(40) NOT NULL,
  ref_id VARCHAR(120) NULL,
  idempotency_key VARCHAR(320) NULL,
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  direction VARCHAR(16) NOT NULL DEFAULT 'out',
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  reference_table VARCHAR(80) NULL,
  reference_id VARCHAR(120) NULL,
  description TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_transactions_invoice (invoice),
  UNIQUE KEY uq_transactions_idempotency_key (idempotency_key),
  KEY idx_transactions_user_id (user_id),
  KEY idx_transactions_transaction_type (transaction_type),
  KEY idx_transactions_created_at (created_at),
  CONSTRAINT fk_transactions_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice VARCHAR(80) NOT NULL,
  provider_invoice VARCHAR(80) NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  total_bayar DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  payment_type VARCHAR(40) NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'web',
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  qr_image TEXT NULL,
  qr_raw TEXT NULL,
  qty INT UNSIGNED NOT NULL DEFAULT 1,
  buyer_whatsapp VARCHAR(40) NULL,
  buyer_name VARCHAR(120) NULL,
  client_ref_id VARCHAR(120) NULL,
  modal_price DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  sell_price DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  reseller_profit DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  order_invoice VARCHAR(80) NULL,
  raw_response JSON NULL,
  status_response JSON NULL,
  target_whatsapp VARCHAR(40) NULL,
  processed_at TIMESTAMP NULL,
  expired_at TIMESTAMP NULL,
  canceled_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payments_invoice (invoice),
  UNIQUE KEY uq_payments_user_client_ref (user_id, client_ref_id),
  KEY idx_payments_provider_invoice (provider_invoice),
  KEY idx_payments_user_id (user_id),
  KEY idx_payments_status (status),
  KEY idx_payments_expired_at (expired_at),
  KEY idx_payments_product_id (product_id),
  CONSTRAINT fk_payments_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_payments_product_id FOREIGN KEY (product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deposits (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice VARCHAR(80) NOT NULL,
  provider_invoice VARCHAR(80) NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  total_bayar DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  payment_type VARCHAR(40) NOT NULL DEFAULT 'deposit',
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  qr_data TEXT NULL,
  qr_image TEXT NULL,
  qr_raw TEXT NULL,
  external_response JSON NULL,
  external_status_response JSON NULL,
  processed_at TIMESTAMP NULL,
  expired_at TIMESTAMP NULL,
  canceled_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_deposits_invoice (invoice),
  KEY idx_deposits_provider_invoice (provider_invoice),
  KEY idx_deposits_user_id (user_id),
  KEY idx_deposits_status (status),
  KEY idx_deposits_payment_type (payment_type),
  KEY idx_deposits_expired_at (expired_at),
  CONSTRAINT fk_deposits_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice VARCHAR(80) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  payment_invoice VARCHAR(80) NULL,
  product_name VARCHAR(180) NOT NULL,
  email_account VARCHAR(255) NULL,
  password_account TEXT NULL,
  payment_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  provider_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  order_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  target_whatsapp VARCHAR(40) NULL,
  delivery_status ENUM('pending','sent','failed','manual_pending') NOT NULL DEFAULT 'pending',
  delivery_time TIMESTAMP NULL,
  raw_response JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_orders_invoice (invoice),
  UNIQUE KEY uq_orders_payment_invoice (payment_invoice),
  KEY idx_orders_user_id (user_id),
  KEY idx_orders_payment_invoice (payment_invoice),
  KEY idx_orders_product_id (product_id),
  CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_orders_product_id FOREIGN KEY (product_id) REFERENCES products(id),
  CONSTRAINT fk_orders_payment_invoice FOREIGN KEY (payment_invoice) REFERENCES payments(invoice)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS withdraws (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  invoice VARCHAR(80) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  fee DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  bank_name VARCHAR(120) NULL,
  account_number VARCHAR(120) NULL,
  account_name VARCHAR(180) NULL,
  admin_note TEXT NULL,
  approved_at TIMESTAMP NULL,
  rejected_at TIMESTAMP NULL,
  processed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_withdraws_invoice (invoice),
  KEY idx_withdraws_user_id (user_id),
  KEY idx_withdraws_status (status),
  CONSTRAINT fk_withdraws_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS saldo_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(40) NOT NULL DEFAULT 'adjustment',
  balance_before DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  before_saldo DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  after_saldo DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  log_type VARCHAR(40) NOT NULL DEFAULT 'unknown',
  reference VARCHAR(120) NULL,
  notes TEXT NULL,
  reference_table VARCHAR(80) NULL,
  reference_id VARCHAR(120) NULL,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_saldo_logs_user_id (user_id),
  KEY idx_saldo_logs_created_at (created_at),
  CONSTRAINT fk_saldo_logs_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS saldo_mutations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  mutation_type VARCHAR(60) NOT NULL DEFAULT 'unknown',
  direction VARCHAR(16) NOT NULL DEFAULT 'neutral',
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  balance_before DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  locked_before DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  locked_after DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  reference_table VARCHAR(80) NULL,
  reference_id VARCHAR(120) NULL,
  description TEXT NULL,
  metadata JSON NULL,
  reference VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_saldo_mutations_user_id (user_id),
  KEY idx_saldo_mutations_mutation_type (mutation_type),
  KEY idx_saldo_mutations_created_at (created_at),
  CONSTRAINT fk_saldo_mutations_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  target_role VARCHAR(40) NULL,
  title VARCHAR(180) NOT NULL,
  message TEXT NOT NULL,
  channel VARCHAR(40) NOT NULL DEFAULT 'in_app',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  read_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_notifications_user_id (user_id),
  KEY idx_notifications_target_role (target_role),
  KEY idx_notifications_is_active (is_active),
  CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  setting_key VARCHAR(120) NOT NULL,
  setting_value TEXT NULL,
  value_type VARCHAR(32) NOT NULL DEFAULT 'string',
  is_secret TINYINT(1) NOT NULL DEFAULT 0,
  description TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_settings_setting_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  actor_id BIGINT UNSIGNED NULL,
  scope VARCHAR(40) NOT NULL DEFAULT 'SYSTEM',
  message TEXT NULL,
  activity TEXT NULL,
  actor_role ENUM('admin','reseller','member') NULL,
  action VARCHAR(120) NOT NULL DEFAULT '',
  entity_type VARCHAR(80) NULL,
  entity_id VARCHAR(120) NULL,
  ip_address VARCHAR(64) NULL,
  user_agent TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_activity_logs_user_id (user_id),
  KEY idx_activity_logs_created_at (created_at),
  CONSTRAINT fk_activity_logs_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS finance_daily_summaries (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  summary_date DATE NOT NULL,
  total_deposit DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  total_withdraw DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  total_order DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  total_profit DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  total_mutation DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_finance_daily_summaries_summary_date (summary_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS balance_mutations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  mutation_type VARCHAR(40) NOT NULL DEFAULT 'unknown',
  direction VARCHAR(16) NOT NULL DEFAULT 'neutral',
  amount DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  balance_before DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  balance_after DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT 0.00,
  source_type VARCHAR(80) NULL,
  source_ref VARCHAR(120) NULL,
  admin_executor_id BIGINT UNSIGNED NULL,
  notes TEXT NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_balance_mutations_user_id (user_id),
  KEY idx_balance_mutations_type_created (mutation_type, created_at),
  KEY idx_balance_mutations_source_ref (source_ref),
  CONSTRAINT fk_balance_mutations_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  admin_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL DEFAULT '',
  target_type VARCHAR(80) NULL,
  target_id VARCHAR(120) NULL,
  ip_address VARCHAR(64) NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_admin_logs_admin_id (admin_id),
  KEY idx_admin_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS webhook_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider VARCHAR(40) NOT NULL DEFAULT 'premku',
  payload JSON NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'received',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_webhook_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS provider_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  provider VARCHAR(40) NOT NULL DEFAULT 'premku',
  action VARCHAR(80) NOT NULL DEFAULT '',
  status VARCHAR(40) NOT NULL DEFAULT 'unknown',
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_provider_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS websocket_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_name VARCHAR(120) NOT NULL,
  target_user_id BIGINT UNSIGNED NULL,
  target_role ENUM('admin','reseller','member') NULL,
  payload JSON NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  delivered_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_websocket_events_target_user_id (target_user_id),
  KEY idx_websocket_events_target_role (target_role),
  KEY idx_websocket_events_status (status),
  KEY idx_websocket_events_created_at (created_at),
  CONSTRAINT fk_websocket_events_target_user_id FOREIGN KEY (target_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS temp_notifications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  target_role ENUM('admin','reseller','member') NULL,
  message TEXT NOT NULL,
  payload JSON NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_temp_notifications_user_id (user_id),
  KEY idx_temp_notifications_target_role (target_role),
  KEY idx_temp_notifications_expires_at (expires_at),
  CONSTRAINT fk_temp_notifications_user_id FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS realtime_cache (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cache_key VARCHAR(180) NOT NULL,
  cache_value JSON NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_realtime_cache_cache_key (cache_key),
  KEY idx_realtime_cache_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS polling_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  poll_type VARCHAR(60) NOT NULL,
  reference_id VARCHAR(120) NULL,
  status VARCHAR(60) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  response_time_ms INT UNSIGNED NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_polling_logs_poll_type (poll_type),
  KEY idx_polling_logs_reference_id (reference_id),
  KEY idx_polling_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
